---
slug: history_of_a_thriving_codebase
filename: history_of_a_thriving_codebase
title: History of a Thriving Codebase
subtitle: A pragmatic guide to Git workflows, tools, and best practices
description: Change me.
author: Peter Brown and Brett Chalupa
copyright: 2014
uuid: cb12fe72-bf9e-4fd3-9da7-c33c82751649
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
